### ISSUE TITLE
Error in performing WGCNA

### ISSUE THREAD

**Issue by SrijaniBagchi** [ELELAB/CAncer-bioMarker-Prediction-Pipeline-CAMPP#2]
I have performed DAA on glycandata.xlsx and now want to run WGCNA on it. If I use glycandata.xlsx as the input(according to the CAMPP manual), it gives the following error.

Error: WGCNA may be performed with either results of differential abundance / expression analysis (DA / DE) or with all variables (ALL). N.B It is not advisable to run WGCNA with all variables if n > 5000. This will make WGCNA slow and plots will be difficult to iterpret. If 'ALL' is chosen and n > 5000, NO plots will be generated, but module variable interconnectivity scores will still be computed.
Execution halted

However on performing WGCNA on glycandata_DE.xlsx(result of DA Analysis), it says:

Warning messages:
1: In lapply(my.data, as.numeric) : NAs introduced by coercion
2: In lapply(my.data, as.numeric) : NAs introduced by coercion
3: In lapply(my.data, as.numeric) : NAs introduced by coercion

- The input data has between 37.5% - 37.5% missing values per row.
- Variables (rows) with more than 70% missing values will be removed.

- The input data has between 0% - 100% missing values per column.
- Samples (rows) with more than 80% missing values will be removed. Variables (rows) with more than 50% missing values are imputed using the overall mean per sample.
... Performing missing value imputation. N.B Uncertainty increases with number of missing values!.
Error in ReplaceNAs(arg.data) : object 'varnames' not found
Execution halted

What should the input for WGCN Analysis?

**Comment by ThildeBT** [comment]
Dear @SrijaniBagchi,

Could you please send me the command line you use, as well as information about the version of R you have?
I just tried with this command line and it worked:

Rscript CAMPP.R -d DataExamples/glycandata.xlsx -m DataExamples/glycanmetadata.xlsx -v ms -g sids,cn -b pool -t log2 -w ALL

I see there is an error in the Manual on how to run WGCNA I have corrected that now and I will push a new version to github. Sorry about that :-) 

Cheers,

Thilde

**Comment by SrijaniBagchi** [comment]
I ran the WGCNA with the command you suggested on my data and it runs partially before giving the following error: Error in hclust(dist(MEDiss), method = "ward.D2") : N must be at least 2.
Calls: WGCNAAnalysis -> hclust
Execution halted
Could you please guide why this error arises for my data in particular? Here is my data matrix and metadata.
[newdata.xlsx](https://github.com/ELELAB/CAncer-bioMarker-Prediction-Pipeline-CAMPP/files/4812158/newdata.xlsx)
[metadata.xlsx](https://github.com/ELELAB/CAncer-bioMarker-Prediction-Pipeline-CAMPP/files/4812159/metadata.xlsx)

**Comment by ThildeBT** [comment]
@SrijaniBagchi,

Yes I will give it a look, but please provide me with:
1. The command you use
2. Your R-version?

**Comment by SrijaniBagchi** [comment]
1. Command Line is MacOSX Catalina Terminal
2. R version 4.0.0 (2020-04-24)

I used the command: Rscript CAMPP.R -d newdata.xlsx -m metadata.xlsx -v array -g Accession,Code -t log2 -w ALL -n WGCNAresult

Thanks for the help.

**Comment by ThildeBT** [comment]
Dear @SrijaniBagchi,

Okay, so your problem seems to be the cut-off for the smallest module size. By default, this parameter is set to 10 variables. In your case, this means that all your variables get clustered together because you have "few" variables and they are similar, e.g. the next split is less than 10. 

There is an easy way around this. You could for example set the min. module size to 5, or look into changing the dissimilarity threshold for merging two modules together. 
The flag **-x** in CAMPP can handle that. Currently, the default values are 10, 25, 25 (min module size, % dissimilarity, % of top-most interconnected variables from each module. But maybe for you, it could be something like 5,25,25. 

So, something like this:
_Rscript CAMPP.R -d newdata.xlsx -m metadata.xlsx -v array -g Accession,Code -t log2 -w ALL -x 5,25,25 -n WGCNAresult_

Alternatively, you can also leave it and say you only want the one modules, I have modified the code to be able to handle this and pushed the new version to the repository just now.

**N.B** Either way, I encourage you to read about these parameters in the WGCNA manual here: to understand what they mean exactly. 
https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/

I have now added an "error" message to the pipeline WGCNA part if this should happen to other people as well :-)

Cheers,

Thilde

**Comment by ThildeBT** [comment]
@SrijaniBagchi, please let me know if things work, so I can close this issue :-) 

Cheers,

**Comment by SrijaniBagchi** [comment]
@ThildeBT , thanks a lot for the help. It works perfectly on my data now.

Regards,
