### ISSUE TITLE
Error in makeContrasts("arg.groupC3-TAG-arg.groupILC-Pik3Ca/Cdh1Null",  : 

### ISSUE THREAD

**Issue by xhhwhc** [ELELAB/CAncer-bioMarker-Prediction-Pipeline-CAMPP#4]
Error in makeContrasts("arg.groupC3-TAG-arg.groupILC-Pik3Ca/Cdh1Null",  : 
  The levels must by syntactically valid names in R, see help(make.names).  Non-valid names: arg.groupC3-TAG,arg.groupILC-Pik3Ca/Cdh1Null,arg.groupKPB-1A,arg.groupKPB-1B,arg.groupKPB-Primary,arg.groupKPB25L-Apobec,arg.groupKPB25L-UV,arg.groupNML-BALBC,arg.groupNML-FVB,arg.groupp53-2151,arg.groupp53-2153F,arg.groupp53-2224,arg.groupp53-2224L,arg.groupp53-2225L,arg.groupp53-2245,arg.groupp53-2336R,arg.groupp53-9263-3,arg.groupp53-T1,arg.groupp53-T12,arg.groupp53-T2,arg.groupp53-T6,arg.groupp53-T7,arg.groupT11-Apobec,arg.groupT11-UV
Calls: eval -> eval -> eval -> makeContrasts
Execution halted

**Comment by ThildeBT** [comment]
Hi @xhhwhc,
As you see from the error message, the issue is your group names. You have a bunch of "special" characters in these names that the makeContrasts function does not like, this is also stated as a potential issue in the pipeline manual.
So my idea would be to do a search and replace in your file. 
Replace the **"/"** and **importantly** the **"-"** with an **"_"**.
You might also consdier replacing the **","** with a **"."**, however I am not sure this is absolutely necessary.

Cheers,
Thilde
